### ISSUE TITLE
CloudSim SDN-NFV

### ISSUE THREAD

**Issue by danivasKavya** [Cloudslab/cloudsimsdn#14]
Hi,
I have few questions regarding CloudSim SDN-NFV-
  1) What is the unit of arrival time of packets specified in workload file? Second? milli seconds?
  2) Observing the Output in console- I have tried giving input file with a packet arrival time between (0-0.360) but the simulator console executes till 7.067199996. how does simulator converts arrival time of packet to cloudsim.clock?
  3) May I know if it possible to force the simulator to duplicate VNF at certain time?

Answers will be appreciated. Thank you

**Comment by hetianzhang** [comment]
Hi,

1. It is second by default. But you can assume the time unit by yourself as it is in the simulation environment.
2. The CloudSim runs till 7.06 may due to the simulation of packet processing time and transmission time. Note that there is also real execution time of simulation code.
3. Yes, you can. For example, at a certain time, you can create a self-defined event that triggers the VNF duplication operation.

Sorry for the late reply.

Kind regards

**Comment by danivasKavya** [comment]
Thank you for your reply. I had a doubt if we can observe packet loss during autoscaling process?

Sorry for asking more questions. I am trying to perform certain experiment in the simulator.

**Comment by hetianzhang** [comment]
I'm afraid not. We simply assume that before a new VNF start, all flows just go through the same SFC. When the new VNF is ready, some packets will be sent through the new VNF according to the load balance algorithm.

For the processing components (switches, hosts, VMs, VNFs), you can either set a buffer (backlog) to store the packets or a timeout (e.g. 2s). In order to simulate the packet loss, you can simply discard the packet (send an EVENT) for an overflow/timeout packet. In addition, you can set the packet loss rate based on real data statistics.

**Comment by danivasKavya** [comment]
Hi, 

Can somebody please tell me what is the unit of Bandwidth of links given in virtual topology file?

Kind regards

**Comment by SDS2Project** [comment]
Hi
Can u plz help me with installation of CloudSimSDN-NFV. I recently started to use the simulator and want to build a security controller that initiate virtual security functions.  
I tried to follow the github but I cannot install it. and it also does not have some files like jars, doc, ... which I can see in cloudsim 3.
Thanks a lot for your help

**Comment by hetianzhang** [comment]
Hi,

> Hi,
> 
> Can somebody please tell me what is the unit of Bandwidth of links given in virtual topology file?

The answer from the original author is "it could be any unit you like".
I also have a hard time figuring it out. In some of his papers, he used MBytes/s.

So the solution is to create your own physical and virtual file with your desired bandwidth unit for example (Mbps).
> 
> Kind regards

**Comment by hetianzhang** [comment]
Hi,

> Hi
> Can u plz help me with installation of CloudSimSDN-NFV. I recently started to use the simulator and want to build a security controller that initiate virtual security functions.
> I tried to follow the github but I cannot install it. and it also does not have some files like jars, doc, ... which I can see in cloudsim 3.
> Thanks a lot for your help

Please check the details of the installation which includes all the details, such as pox file to get the jars you need and how to include the CloudSim.
