### ISSUE TITLE
BUILD FAILURE - cloudsimsdn: Compilation failure

### ISSUE THREAD

**Issue by wyz-eno** [Cloudslab/cloudsimsdn#23]
/D:/... .../cloudsimsdn-master/cloudsimsdn-master/src/main/java/org/cloudbus/cloudsim/sdn/virtualcomponents/VirtualNetworkMapper.java:[6,29] couldn't find symbol.

A lot .java couldn't find symbols and .core doesn't exist.

**Comment by magaboomchen** [comment]
Hi, I meet the same problem in windows.
Then, I try to install cloudsimSDN in ubuntu 16.04.
I meet this problem again.

@jayjmin @manoelcampos 
I find the problem is caused by a wrong download link of cloudsim-4.0.tar.gz
provided by the installation in page: https://github.com/Cloudslab/cloudsimsdn/releases

You have to goto the cloudsim repository https://github.com/Cloudslab/cloudsim/releases
and download the cloudsim-4.0.tar.gz there.

Then decompress the cloudsim-4.0.tar.gz and copy cloudsim-4.0/jars/cloudsim-4.0.jar to the diretory of cloudsimsdn

Good luck!

**Comment by hetianzhang** [comment]
Hi @wyz-eno

To clarify any confusion, I simply update the dependency guideline. Please check.
Hope you can run the simulator now.

Regards

**Comment by hetianzhang** [comment]
Hi @magaboomchen 

To clarify any confusion, I simply update the dependency guideline. Please check.
Hope you can run the simulator now.
> Hi, I meet the same problem in windows.
> Then, I try to install cloudsimSDN in ubuntu 16.04.
> I meet this problem again.
> 
> @jayjmin @manoelcampos
> I find the problem is caused by a wrong download link of cloudsim-4.0.tar.gz
> provided by the installation in page: https://github.com/Cloudslab/cloudsimsdn/releases
> 
> You have to goto the cloudsim repository https://github.com/Cloudslab/cloudsim/releases
> and download the cloudsim-4.0.tar.gz there.
> 
> Then decompress the cloudsim-4.0.tar.gz and copy cloudsim-4.0/jars/cloudsim-4.0.jar to the diretory of cloudsimsdn
> 


If my memory serves well, the jar included in the https://github.com/Cloudslab/cloudsimsdn/releases/tag/v2.0.1-beta is the newest version.

For the jar file provided by [Cloudsim4.0 release](https://github.com/Cloudslab/cloudsim/releases/tag/cloudsim-4.0), I can not guarantee that it is based on the newest version. 
Anyway, I deleted the jar file provided by the CloudSimSDN-NFV release.
Please follow the dependency guideline to export the jar by yourself if you encountered any bugs during the running.

> Good luck!
